<a href="https://colab.research.google.com/github/hisanakanishi/python-basic-kadai/blob/main/kadai_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [6]:
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3,],[4,5,6,7]])
C = np.dot(A, B)
print(C)
max_C = C.max()
max_C

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47